[build-system]
requires = ["setuptools", "wheel", "toml"]

[tool.black]
line-length = 120

[erl]
erl_dependencies = ["erl_cmake_tools", "erl_common", "erl_covariance"]
build_type = "Release"
use_libtorch = "ON"

[project]
name = "erl_geometry"
version = "0.2.0"
description = "Python package for erl_geometry"
authors = [
    { name = "Zhirui Dai", email = "zhdai@ucsd.edu" }
]
maintainers = [
    { name = "Zhirui Dai", email = "zhdai@ucsd.edu" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
dependencies = [
    "setuptools",
    "numpy",
    "torch>=2.7",
    "open3d",
]
